#!/bin/bash
echo "Best school" > [D[D[D[D[D[D[D[D[C[[CS[C[C[C[C School[A[B" > \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)"[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D"/[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)"
